### ISSUE TITLE
Annotate JS

### ISSUE THREAD

**Issue by kishandonepudi** [bhargavacc/pdf-annotation#3]
Can i use this in ionic app based on angular 2+ ?.

can you please let me know how..

thanks for ur time

**Comment by bhargavacc** [comment]
Hi Kishan,

Thanks for your message.

I never tried with the Angular2 ionic APP platform. But as per my understanding, it will not work because this plugin developed in Angular1.4 which is completely different than the newer version.

Please let me know if you need any help from my end.

Regards,
Bhargav
